# Generated by Django 3.1.2 on 2021-01-04 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acme', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ammo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ammo_name', models.CharField(max_length=100)),
                ('itm_no', models.CharField(max_length=100)),
                ('un_no', models.CharField(max_length=100)),
                ('cl_div', models.CharField(max_length=100)),
                ('m_no', models.CharField(max_length=100)),
            ],
        ),
    ]
