# Generated by Django 3.1.2 on 2021-01-04 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acme', '0006_remove_inout_authorizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='inout',
            name='authorizer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='acme.authorizer'),
        ),
    ]
