# Generated by Django 3.1.2 on 2021-01-05 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acme', '0007_inout_authorizer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorizer',
            name='password',
        ),
    ]
