# Generated by Django 3.1.2 on 2021-01-05 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acme', '0009_authorizer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorizer',
            name='user',
        ),
    ]
