# Generated by Django 3.1.2 on 2021-01-05 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acme', '0010_remove_authorizer_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=200)),
                ('in_time', models.TimeField()),
                ('temperature', models.CharField(max_length=200, null=True)),
                ('humidity', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
