# Generated by Django 3.1.2 on 2021-01-05 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acme', '0011_weather'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weather',
            old_name='in_time',
            new_name='time',
        ),
    ]
