# Generated by Django 3.1.2 on 2021-01-05 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acme', '0014_stock_deficiency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='deficiency',
        ),
    ]
