# Generated by Django 3.1.2 on 2021-01-06 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acme', '0017_auto_20210107_0000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='deficiency',
        ),
    ]
