# Generated by Django 3.1.2 on 2021-01-07 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acme', '0019_issuer'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='deficiency',
            field=models.IntegerField(null=True),
        ),
    ]
