# Generated by Django 3.1.2 on 2021-01-07 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acme', '0025_remove_stock_deficiency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_no', models.CharField(max_length=200, null=True)),
                ('amount', models.IntegerField(default=0, null=True)),
                ('reason', models.CharField(max_length=200, null=True)),
                ('date', models.DateField(max_length=200)),
                ('qm_permission', models.BooleanField(default=False)),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acme.issuer')),
            ],
        ),
    ]
