# Generated by Django 3.1.2 on 2021-01-07 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acme', '0027_issue_ammo'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='stock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='acme.stock'),
        ),
    ]
