# Generated by Django 3.1.2 on 2021-01-08 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acme', '0032_auto_20210108_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason', models.CharField(max_length=200, null=True)),
                ('empty_case', models.IntegerField(default=0, null=True)),
                ('extra', models.IntegerField(default=0, null=True)),
                ('deficiency', models.IntegerField(default=0, null=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acme.issue')),
            ],
        ),
    ]
