# Generated by Django 3.1.2 on 2021-01-08 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acme', '0033_deposit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='issue',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='ammo',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='stock',
        ),
        migrations.AddField(
            model_name='issue',
            name='stock',
            field=models.ManyToManyField(to='acme.Stock'),
        ),
    ]
