# Generated by Django 3.1.2 on 2021-01-08 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acme', '0034_auto_20210108_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='ammo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='acme.ammo'),
        ),
        migrations.RemoveField(
            model_name='issue',
            name='stock',
        ),
        migrations.AddField(
            model_name='issue',
            name='stock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='acme.stock'),
        ),
    ]
