# Generated by Django 3.1.2 on 2021-01-08 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acme', '0037_deposit_issuer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='ammo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acme.ammo'),
        ),
    ]
