# Generated by Django 3.1.2 on 2021-01-08 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acme', '0039_auto_20210108_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='issue',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='acme.issue'),
        ),
    ]
