# Generated by Django 3.1.2 on 2021-01-08 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acme', '0040_auto_20210108_2128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(default=0)),
                ('date', models.DateField(null=True)),
                ('lot_no', models.CharField(max_length=200, null=True)),
                ('co_permission', models.BooleanField(default=False)),
                ('stock', models.ManyToManyField(to='acme.Stock')),
            ],
        ),
    ]
