# Generated by Django 3.1.2 on 2021-01-08 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acme', '0041_demand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demand',
            name='lot_no',
        ),
        migrations.AddField(
            model_name='demand',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='deficiency',
            field=models.IntegerField(null=True),
        ),
    ]
