# Generated by Django 3.1.2 on 2021-01-09 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acme', '0043_auto_20210109_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='demand',
            name='serial',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='deficiency',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='empty_case',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='extra',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='amount',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='amount',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='auth',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='deficiency',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='serial',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
