# Generated by Django 3.1.2 on 2021-01-10 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acme', '0045_auto_20210110_0917'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='line',
            name='line',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='acme.linename'),
        ),
    ]
