# Generated by Django 3.1.2 on 2021-01-10 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acme', '0047_auto_20210110_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='ammo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acme.ammo'),
        ),
    ]
