# Generated by Django 3.1.2 on 2021-01-10 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acme', '0048_auto_20210110_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='line',
            name='no',
        ),
        migrations.AlterField(
            model_name='lot',
            name='ammo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='acme.ammo'),
        ),
    ]
