# Generated by Django 3.1.2 on 2021-01-10 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acme', '0049_auto_20210110_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='acme.linename'),
        ),
    ]
