# Generated by Django 3.1.2 on 2021-01-10 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acme', '0050_auto_20210110_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='line',
            name='ammo',
        ),
    ]
