# Generated by Django 3.1.2 on 2021-01-10 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acme', '0052_line_ammo'),
    ]

    operations = [
        migrations.AddField(
            model_name='linename',
            name='ammo',
            field=models.ManyToManyField(to='acme.Ammo'),
        ),
        migrations.AddField(
            model_name='linename',
            name='amount',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
