# Generated by Django 3.1.2 on 2021-01-10 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acme', '0053_auto_20210110_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linename',
            name='ammo',
        ),
        migrations.AddField(
            model_name='linename',
            name='ammo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='acme.ammo'),
        ),
    ]
