# Generated by Django 3.1.2 on 2021-01-10 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acme', '0054_auto_20210110_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linename',
            name='ammo',
        ),
        migrations.RemoveField(
            model_name='linename',
            name='amount',
        ),
    ]
