# Generated by Django 3.1.2 on 2021-01-10 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acme', '0058_auto_20210110_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turningover',
            name='linename1',
        ),
        migrations.AddField(
            model_name='turningover',
            name='ammoline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='acme.ammoline'),
        ),
    ]
