# Generated by Django 3.1.2 on 2021-01-10 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acme', '0059_auto_20210110_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='lot_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='acme.lot'),
        ),
    ]
