# Generated by Django 3.1.2 on 2021-01-10 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acme', '0061_ledger'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leadger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('issue', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='acme.issue')),
                ('line', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='acme.line')),
            ],
        ),
        migrations.DeleteModel(
            name='Ledger',
        ),
    ]
