# Generated by Django 3.1.2 on 2021-01-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acme', '0062_auto_20210110_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadger',
            name='amount',
            field=models.IntegerField(null=True),
        ),
    ]
