# Generated by Django 3.1.2 on 2021-01-10 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acme', '0065_leadger'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Leadger',
        ),
    ]
